### ISSUE TITLE
License ID

### ISSUE THREAD

**Issue by jperedadnr** [5-pengoo/Therabot#11]
You shouldn't publish your license ID. 

Remove the line `@License(key=...`.

You can create the file `src/main/resources/gluonmobile.license` and simply paste the ID there, and then don't commit such file to the repository.

**Comment by ariettag** [comment]
I just made the repo private. Normally, it is private, which is why I left my license ID there; I just opened it up for you to join. In the future, if I make it public, I will probably do that.
