### ISSUE TITLE
"package com.gluonhq.attach.browser does not exist" in BrowseUtils.java

### ISSUE THREAD

**Issue by ariettag** [5-pengoo/Therabot#13]
import com.gluonhq.attach.browser.BrowserService; is giving me an error. It says "package com.gluonhq.attach.browser does not exist".  Subsequent errors are also caused by this issue.

**Comment by jperedadnr** [comment]
It works fine for me. I've just cloned your repo and `mvn javafx:run` works.

Try to run `mvn clean -U javafx:run`
