### ISSUE TITLE
Graph Messing Up

### ISSUE THREAD

**Issue by ariettag** [5-pengoo/Therabot#17]
@jperedadnr I noticed that each data point on the graph that accumulates with user data entries becomes one straight line. For instance, if the difference between the moods before and after using Therabot is 20 mood points, each entry's difference will show up as 20 points. I have attached a picture for further context.
Normally, I would not bug you with issues not related to Gluon, but this did seem to happen right after you changed the way files are stored in the app. Of course, I really appreciate the fact that you fixed it and would probably be back to square one if it wasn't for your help, however, I am not familiar with this way of doing things so I am unable to find the root of the issue.
![IMG_F1DB9A5550D9-1](https://user-images.githubusercontent.com/79435335/130364849-1d06f194-7514-470a-bdeb-f4854f52d5fe.jpeg)

**Comment by ariettag** [comment]
Hello @jperedadnr,
I checked, and it seems that the code that creates the graph hasn't changed since it previously worked, so I think it may be something with the new file type. Could you please help me out? Thank you so much.

**Comment by jperedadnr** [comment]
Do you see the same issue if you run on desktop:
```
mvn gluonfx:run
```
?
Then add some printouts to the serialization operations (reading/writing) and see if there is some wrong value?

**Comment by ariettag** [comment]
Ok, I did that. After some troubleshooting, I figured it out. Thank you!
