### ISSUE TITLE
Tried to Rename Bundle ID and Failed

### ISSUE THREAD

**Issue by ariettag** [5-pengoo/Therabot#18]
Hello @jperedadnr,
I may have just done something very stupid.
I was trying to upload my generated .ipa file, but the Transporter was giving me the below error. So, I thought it would be a good idea to refactor my Gluon project and rename the Bundle ID from com.mysecondapplication.MySecondApplication to com.superpengoo.Therabot. Now, I am getting the below error. Please help!
<img width="262" alt="Screen Shot 2021-09-06 at 12 48 04 PM" src="https://user-images.githubusercontent.com/79435335/132257134-23733ebb-6745-4064-bb48-1d0a399b12be.png">
[process-compile-1630957454374.log](https://github.com/5-pengoo/Therabot/files/7117691/process-compile-1630957454374.log)

**Comment by jperedadnr** [comment]
It is okay to refactor the project, of course, but you have to do it carefully. Your log says that the "new" main class is not found, and native-image failed. It is not possible to have an IPA without native-image working.

Go step by step again: 
Make sure your pom is updated, run `mvn clean`, and make sure there are no results if you search "com.mysecondapplication" or "MySecondApplication".
- Run `mvn gluonfx:run` and see that your refactored project works fine. Don't go any further if this doesn't work!
- Then run `mvn -Pios gluonfx:build` and see that the native image is created and link works
- Then `mvn -Pios gluonfx:package`, and see that you have your IPA file created. Make sure that your bundleID in your provisioning profile is also updated (probably you will need to create a new one).
- Then try Transporter again with this new IPA.

**Comment by ariettag** [comment]
Ok @jperedadnr,
I'm able to clean and run, however when I try building, I get the below error, which I'm having trouble deciphering.
[client-debug0.log](https://github.com/5-pengoo/Therabot/files/7117738/client-debug0.log)

**Comment by ariettag** [comment]
@jperedadnr I think I was able to decipher it; the native image is not able to be created. Side note: I do remember that every time I would build in the past, it would say that it couldn't find a native image and that it was ignoring the error.

**Comment by jperedadnr** [comment]
You still have references to your old main class. Do a full search under your src folder. I also suggest you remove the files under resources/META-INF and run `gluonfx:runagent` again

**Comment by ariettag** [comment]
@jperedadnr I followed your suggestions in your comment above, and then ran `mvn -Pios gluonfx:build`. Now, it is telling me that I don't have a valid Identity. The identity that I specified in my pom.xml was obtained through my client debug log. I would attach the log printed from this run, but it seems to be an old log for some reason so I will paste the error statement here instead.

```==================== LINK TASK ====================
[Mon Sep 06 14:24:25 PDT 2021][INFO] Default iOS plist generated in /Users/superpengooooo/NetBeansProjects/Therabot/target/gluonfx/arm64-ios/gensrc/ios/Default-Info.plist.
Consider copying it to /Users/superpengooooo/NetBeansProjects/Therabot/src/ios before performing any modification
[Mon Sep 06 14:24:33 PDT 2021][INFO] Default iOS resources generated in /Users/superpengooooo/NetBeansProjects/Therabot/target/gluonfx/arm64-ios/gensrc/ios.
Consider copying them to /Users/superpengooooo/NetBeansProjects/Therabot/src/ios before performing any modification
java.lang.RuntimeException: No valid Identity (Certificate) found for iOS development.
Please check https://docs.gluonhq.com/client/ for more information.
	at com.gluonhq.substrate.util.ios.CodeSigning.assertValidIdentity(CodeSigning.java:119)
	at com.gluonhq.substrate.util.ios.CodeSigning.signApp(CodeSigning.java:103)
	at com.gluonhq.substrate.target.IosTargetConfiguration.link(IosTargetConfiguration.java:188)
	at com.gluonhq.substrate.SubstrateDispatcher.nativeLink(SubstrateDispatcher.java:438)
	at com.gluonhq.NativeLinkMojo.execute(NativeLinkMojo.java:47)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:28 min
[INFO] Finished at: 2021-09-06T14:24:33-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.3:link (default-cli) on project Therabot: Error: No valid Identity (Certificate) found for iOS development.
[ERROR] Please check https://docs.gluonhq.com/client/ for more information.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:32 min
[INFO] Finished at: 2021-09-06T14:24:33-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.3:build (default-cli) on project Therabot: Error, gluonfx:build failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
superpengooooo@Ariettas-MacBook-Pro Therabot % 
```

**Comment by jperedadnr** [comment]
Check (and post) the client-debug.log-1 with the Link task, it should give you more insight.

**Comment by ariettag** [comment]
@jperedadnr Here you go. I had to change the type of file to .log since GitHub didn't support client-debug.log-1. 
[client-debug.log](https://github.com/5-pengoo/Therabot/files/7117893/client-debug.log)

**Comment by jperedadnr** [comment]
Seems incomplete? It doesn't show the error. Maybe you can add `<verbose>true</verbose>` to the plugin's configuration in your pom, and run `mvn -Pios gluonfx:link`, then post the `client-debug.log` (or just a zip with the log folder)

**Comment by ariettag** [comment]
[client-debug0.log.1.zip](https://github.com/5-pengoo/Therabot/files/7117914/client-debug0.log.1.zip)
@jperedadnr let me know if this is better.

**Comment by jperedadnr** [comment]
Hmm, still same, missing all the output form the signing part. Add `<verbose>true</verbose>` to the plugin's configuration in your pom:

```
<plugin>
                <groupId>com.gluonhq</groupId>
                <artifactId>gluonfx-maven-plugin</artifactId>
                <version>${gluonfx.plugin.version}</version>
                <configuration>
                    <target>${gluonfx.target}</target>
                    <attachList>
                        <list>browser</list>
                        <list>display</list>
                        <list>lifecycle</list>
                        <list>statusbar</list>
                        <list>storage</list>
                    </attachList>
                    <mainClass>${mainClassName}</mainClass>
                    <verbose>true</verbose>
                </configuration>
            </plugin>
```
And run `mvn -Pios gluonfx:link gluonfx:package` again, then post the log folder once the process fails.

**Comment by ariettag** [comment]
@jperedadnr that's strange. I did set verbose to true last time. This time, I have attached the entire log file as you suggested. Hopefully 
[log.zip](https://github.com/5-pengoo/Therabot/files/7117931/log.zip)
this will work.

**Comment by jperedadnr** [comment]
Ok, thanks, I see, the log is okay, it is failing to find a valid signing identity.
What is your `<providedSigningIdentity>`?

**Comment by ariettag** [comment]
@jperedadnr `<providedSigningIdentity>
                            iPhone Distribution: Gluon Software BVBA (**********)
 </providedSigningIdentity>`

********** is a ten digit letter/number combo code for "Apple Distribution"

**Comment by jperedadnr** [comment]
that is the Gluon signing identity... you need to use yours. 

Have you created a Certificate yet?  Follow https://docs.gluonhq.com/#platforms_ios_distribution_certificate
and make sure you select *iOS Distribution (App Store and Ad Hoc)* (we don't have support yet for the "Apple Distribution" type).

**Comment by ariettag** [comment]
I see. I tried removing the Gluon part before, but I added it back because I didn't know if it was necessary. The real problem is that I made an Apple Distribution certificate instead of an iOS distribution certificate. I will fix that really quick and let you know if I get the same error.

**Comment by ariettag** [comment]
@jperedadnr I'm still getting an error, unfortunately. 
[log.zip](https://github.com/5-pengoo/Therabot/files/7117987/log.zip)

**Comment by jperedadnr** [comment]
Did you update `providedSigningIdentity`? It should point to your new identity:
```
<providedSigningIdentity>iPhone Distribution: Katina Goshtasby (RP543JY5N7)</providedSigningIdentity>
```

**Comment by ariettag** [comment]
@jperedadnr I didn't include the name, which is what was causing it. Now, I can build successfully. I will continue to go through the steps to upload it and let you know if things stop working. Thank you!

**Comment by ariettag** [comment]
@jperedadnr Now it can't find the Provisioning Profile. Since I last commented on this thread, I replaced the ios files with my app logo and ran the link goal.
[log.zip](https://github.com/5-pengoo/Therabot/files/7118014/log.zip)

**Comment by jperedadnr** [comment]
Did you update the Provisioning profile to use your new Certificate? Once you update it, download it and install it (double click).

**Comment by ariettag** [comment]
@jperedadnr ah yes. I forgot to do that. It works now, thank you!

**Comment by ariettag** [comment]
@jperedadnr I'm getting the attached error in the Transporter, even though I have `Gluon-ipad-app-icon-76@2x.png` in my `AppIcon.appiconset` file. 
<img width="622" alt="Screen Shot 2021-09-06 at 4 55 53 PM" src="https://user-images.githubusercontent.com/79435335/132266496-daa432a6-8d7e-46c3-818e-1915eb5fd893.png">

**Comment by jperedadnr** [comment]
The file https://github.com/5-pengoo/Therabot/blob/master/src/ios/assets/Assets.xcassets/AppIcon.appiconset/Gluon-ipad-app-icon-76%402x.jpeg is a "jpeg", but your content.json refers to "png" (there are maybe others with this issue too). 
Make sure you either use only png format or you update the contents.json file accordingly. I suggest the former.

**Comment by ariettag** [comment]
@jperedadnr ok, I have changed it, and it works now!
I was able to successfully upload the app to App Store Connect, so I suppose I'll close this issue now. Thank you again!
