### ISSUE TITLE
Logging in doesn't work on app

### ISSUE THREAD

**Issue by ariettag** [5-pengoo/Therabot#19]
Hello @jperedadnr,
I have a bit of an issue. Since we last spoke, I uploaded the app to the Apple App Store, which is great, but every time a user tries to log in with an existing account, either the log in button press does nothing or it shows the "Unknown log in." label. Naturally, I was disheartened, but I did some testing on my computer, and a desktop run, `mvn gluonfx:run` works just fine. Considering that I have obviously been able to run test versions of the app on my phone, I am very concerned as to if converting it to an Apple app means that it cannot store data locally. So, I was wondering if you had any knowledge on this issue because I definitely don't want to keep a flawed version of my app on the app store for long.

**Comment by jperedadnr** [comment]
I've just built the app from the repository (which might be really behind your latest code), and when I deploy to my iPhone and create an account with "jp" user, I see:
```
Creating file: /var/mobile/Containers/Data/Application/775A3599-FF26-410A-945D-3A338391FDC7/Library/gluon/jp3398.dat
[Sat Sep 11 01:36:28 CEST 2021][INFO] [SUB] User is not known
```
When I close the app and start again, I can log in. Even if I deploy the app again (the private area with data is not removed) I can see that the file is still there:
```
[Sat Sep 11 01:43:42 CEST 2021][INFO] [SUB] FILE: /var/mobile/Containers/Data/Application/85916574-09E7-4217-B0A6-0CA8427F3086/Library/gluon/jp3398.dat
[Sat Sep 11 01:43:42 CEST 2021][INFO] [SUB] User is known
[Sat Sep 11 01:43:42 CEST 2021][INFO] [SUB] YAY! nv is not null!
[Sat Sep 11 01:43:42 CEST 2021][INFO] [SUB] nv is null
```

Anyway, you can comment out your releaseConfiguration data and deploy with `mvn -Pios gluonfx:nativerun` to directly verify on your phone. The app is the exact same you submit to the Apple Store, so you should get the same issues. Add some printouts to find out if files exist, or what is expected.

If you want me to test your latest version, update the repository.

**Comment by ariettag** [comment]
@jperedadnr I'm happy to hear that the app deployed to the App Store should be the same. I would really appreciate if you could test the latest version, however, I've been having some trouble committing the changes. It keeps producing errors that I have been unable to solve, even after looking them up on the internet. I have attached a video of the errors.

https://user-images.githubusercontent.com/79435335/132960447-f1eb2bfc-9a7a-45ec-b31d-1cf4ead62192.mp4

**Comment by ariettag** [comment]
@jperedadnr for the past month, I've been trying to push my many unsuccessful commits to this repository. I finally decided that the best idea would be to send you a zip (see below link) of the updated project instead. My malfunctioning app is still on the App Store, yet I have had to delay the official release announcement, which, as you can imagine, is extremely frustrating. So, if you could let me know what the problem is with this program ASAP, I would greatly appreciate it. Thank you.
P.s. I forgot to mention that I have already tested it on my phone, and it works there, which just adds to my confusion.
[https://drive.google.com/file/d/1RKnz9Ky4L0BVJTsAdpUtKL_v5j3tTE8N/view?usp=sharing](https://drive.google.com/file/d/1RKnz9Ky4L0BVJTsAdpUtKL_v5j3tTE8N/view?usp=sharing)

**Comment by jperedadnr** [comment]
I've downloaded the zip, removed the target folder, and without doing any
change at your code, I've just run on my desktop:
mvn gluonfx:run -> works
mvn gluonfx:build gluonfx:nativerun -> fails:

 Oct 10, 2021 12:40:44 PM com.superpengoo.views.PrimaryView lambda$new$1

[Sun Oct 10 12:40:44 CEST 2021][INFO] [SUB] SEVERE: null

[Sun Oct 10 12:40:44 CEST 2021][INFO] [SUB]
java.lang.ClassNotFoundException: java.util.ArrayList

[Sun Oct 10 12:40:44 CEST 2021][INFO] [SUB] at
com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:71)

[Sun Oct 10 12:40:44 CEST 2021][INFO] [SUB

I see that the serialization file is empty:
Therabot/src/main/resources/META-INF/native-image/serialization-config.json
and that wasn't the case before:
https://github.com/5-pengoo/Therabot/blob/master/src/main/resources/META-INF/native-image/serialization-config.json

Without this, deserialization (to read your dat files) won't work, and that
explains why you have to create a new account all over again.

As explained before, you can run
mvn gluonfx:runagent
to generate the new json files for native-image, then
mvn gluonfx:build gluonfx:nativerun -> works
and then on iOS, after a fresh install (removing the old app):
mvn -Pios gluonfx:build gluonfx:nativerun -> works

See that it works for you too.

Jose

**Comment by ariettag** [comment]
@jperedadnr I see now, thank you. However, I unfortunately messed something else up, this time with my provisioning profile and certificate. I feel like I should know what the error is, but I do not.

`<providedSigningIdentity>
                            iPhone Distribution: Katina Goshtasby (RP543JY5N7)
                        </providedSigningIdentity>
                        <providedProvisioningProfile>
                             Therabot-new
                        </providedProvisioningProfile>`

<img width="488" alt="Screen Shot 2021-10-13 at 5 38 53 PM" src="https://user-images.githubusercontent.com/79435335/137231380-2fc8d489-e028-4db3-b1b5-05297db5f2a2.png">
<img width="602" alt="Screen Shot 2021-10-13 at 5 42 08 PM" src="https://user-images.githubusercontent.com/79435335/137231600-8db3bc94-8bc8-41e6-aef8-71ca47b5a3fb.png">

<img width="760" alt="Screen Shot 2021-10-13 at 5 41 48 PM" src="https://user-images.githubusercontent.com/79435335/137231579-b0f4c47f-b4d0-4748-b11e-e42cc7c37957.png">

**Comment by jperedadnr** [comment]
You don't mention what is the error. In any case make sure you use the exact names (i.e. no trailing spaces) for provisioning profile and signing identity.

**Comment by ariettag** [comment]
@jperedadnr I deleted the space in front of ```Therabot-new``` but nothing happened. I'll attach the log below. I'm also going to paste some of the terminal output because the log isn't showing the full error.

```[Thu Oct 14 10:58:14 PDT 2021][FINE] Plist at /Users/superpengooooo/NetBeansProjects/Therabot/src/ios/Default-Info.plist
[Thu Oct 14 10:58:14 PDT 2021][FINE] Got Bundle ID = com.superpengoo.Therabot
[Thu Oct 14 10:58:14 PDT 2021][FINE] PB Command for security: security find-identity -p codesigning -v
[Thu Oct 14 10:58:14 PDT 2021][FINE] Start process security...
[Thu Oct 14 10:58:15 PDT 2021][FINE] [SUB]   1) A482933E6DAE06D1DC3E0716AD1BE5FDA00CE2D2 "Apple Development: superpengoo@icloud.com (Y54Z55T4CK)"
[Thu Oct 14 10:58:15 PDT 2021][FINE] [SUB]   2) 6A4E7C76C640F3889D6ACE7CEE2AA6FB9DC012C1 "Apple Development: katinachi@me.com (R56P57D257)"
[Thu Oct 14 10:58:15 PDT 2021][FINE] [SUB]   3) 7CE87E70B3159D3EF805010291052DD703AEDBCC "Apple Distribution: Katina Goshtasby (RP543JY5N7)"
[Thu Oct 14 10:58:15 PDT 2021][FINE] [SUB]   4) 84842A554BB89FD2B113CD1847F624E24C91E9C5 "iPhone Distribution: Katina Goshtasby (RP543JY5N7)"
[Thu Oct 14 10:58:15 PDT 2021][FINE] [SUB]      4 valid identities found
[Thu Oct 14 10:58:15 PDT 2021][FINE] Result for security: 0
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provision asked with bundleId = com.superpengoo.Therabot (initial bundleId: com.superpengoo.Therabot)
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/6d03a6b8-c1bd-453c-8b28-7756af7e2755.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/16215c3a-9e03-4f80-8f60-6a9b42eb3326.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/f3200fb9-7112-49bc-bdbd-6e73b5f81d0a.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/b339eb60-a550-43af-8c9b-afae87747cf3.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/1578d2af-3586-4894-9f1c-b2734ae43b6a.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/d4c45656-e705-49f0-a793-2b9b38ba469b.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/08b79a51-1839-4bb9-95c2-3b3b996f0316.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/fe1210cb-cc45-4b43-a33c-94db21e531a9.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/ff96b862-55c2-43ba-914e-fdab6e4b576e.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/a5df8f31-86ed-480d-9d1a-0e6df72991dd.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/ef82b282-63b6-42ff-94c5-5d737d4b6dae.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/c6a717c6-3ca1-4504-9450-f07ffc5aea96.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/ca45cba5-0d8d-4d36-be4d-99aacbc3c054.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/6759e6d9-3d80-479e-b142-e204dcb041c0.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/08a4bfb3-5184-4c3f-9b4b-87120c1aff4f.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Mobile provisioning profile for /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles/e15be2da-3dd2-4e6a-80a7-234553fc4697.mobileprovision
[Thu Oct 14 10:58:15 PDT 2021][FINE] Checking mobile provision A Self Reflection Application
[Thu Oct 14 10:58:15 PDT 2021][FINE] App identifiers match, but there are not fingerprint matches
[Thu Oct 14 10:58:15 PDT 2021][FINE] Checking mobile provision Therabot
[Thu Oct 14 10:58:15 PDT 2021][FINE] App identifiers match, but there are not fingerprint matches
[Thu Oct 14 10:58:15 PDT 2021][FINE] Checking mobile provision Therabot
[Thu Oct 14 10:58:15 PDT 2021][FINE] App identifiers match, but there are not fingerprint matches
[Thu Oct 14 10:58:15 PDT 2021][FINE] Checking mobile provision Therabot
[Thu Oct 14 10:58:15 PDT 2021][FINE] ari-new-new matches SigningIdentity{name='iPhone Distribution: Katina Goshtasby (RP543JY5N7)', sha1='84842A554BB89FD2B113CD1847F624E24C91E9C5'}
[Thu Oct 14 10:58:15 PDT 2021][INFO] Warning, getProvisioningProfile is failing
[Thu Oct 14 10:58:15 PDT 2021][FINE] Looking for resource: /native/ios/Entitlements.plist
[Thu Oct 14 10:58:15 PDT 2021][FINE] Entitlements.plist = [get-task-allow=false, application-identifier=RP543JY5N7.com.superpengoo.Therabot, keychain-access-groups=com.dd.plist.NSArray@61b6e693, com.apple.developer.team-identifier=RP543JY5N7]
[Thu Oct 14 10:58:15 PDT 2021][FINE] Signing with entitlements path: /Users/superpengooooo/NetBeansProjects/Therabot/target/gluonfx/arm64-ios/gvm/tmp/Entitlements.plist
java.io.IOException: Error signing app: signing identity was null
	at com.gluonhq.substrate.util.ios.CodeSigning.sign(CodeSigning.java:231)
	at com.gluonhq.substrate.util.ios.CodeSigning.signApp(CodeSigning.java:113)
	at com.gluonhq.substrate.target.IosTargetConfiguration.link(IosTargetConfiguration.java:188)
	at com.gluonhq.substrate.SubstrateDispatcher.nativeLink(SubstrateDispatcher.java:438)
	at com.gluonhq.NativeLinkMojo.execute(NativeLinkMojo.java:47)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:33 min
[INFO] Finished at: 2021-10-14T10:58:15-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.3:link (default-cli) on project Therabot: Error: Error signing app: signing identity was null -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:36 min
[INFO] Finished at: 2021-10-14T10:58:15-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.3:build (default-cli) on project Therabot: Error, gluonfx:build failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
superpengooooo@Ariettas-MacBook-Pro Therabot % ```

[client-debug0.log](https://github.com/5-pengoo/Therabot/files/7348326/client-debug0.log)

**Comment by jperedadnr** [comment]
Make sure you don't have empty spaces at the end either. Also you have too many provisioning profiles under /Users/superpengooooo/Library/MobileDevice/Provisioning Profiles
Maybe you can move them to a different location and just keep there the one that you are using. If you Cmd+Click on it from finder you can see its name and certificates (can you paste a screenshot here?). The name should match `Therabot-new`, and the certificate should match name and sha1.
However I see 
```
ari-new-new matches SigningIdentity{name='iPhone Distribution: Katina Goshtasby (RP543JY5N7)', sha1='84842A554BB89FD2B113CD1847F624E24C91E9C5'}
```
so `ari-new-new` is a different profile than  `Therabot-new`. Make sure you use the correct one.

**Comment by ariettag** [comment]
@jperedadnr ok, see attached. Since I'm still a beginner to all of this, I accidentally made too many profiles, but I've since deleted all of them except ```therabot-new``` and ```Ari```. I'm not sure which of the files in ```/Users/superpengooooo/Library/MobileDevice/Provisioning Profiles``` corresponds with ```therabot-new``` (I think I'm command-clicking wrong), and I'm also not sure how to stop it from looking for ```ari-new-new```, which has since been deleted.
<img width="788" alt="Screen Shot 2021-10-14 at 12 27 18 PM" src="https://user-images.githubusercontent.com/79435335/137382846-0dcd7ada-7fe8-483e-8dec-53d665c491e4.png">

**Comment by jperedadnr** [comment]
I mentioned it:
  If you Cmd+Click on it from Finder you can see its name and certificates

**Comment by ariettag** [comment]
Ok, @jperedadnr, for some reason cmd-click wasn't working, but I was able to find the info by right-clicking and then going to "Get Info". I have successfully uploaded the app to the app store, so I'll close this issue when I can confirm that everything works. Thanks for all of your help!

**Comment by jperedadnr** [comment]
Cool !
My bad, you select file and press Space bar to activate the preview.
