### ISSUE TITLE
Android Build Not Working

### ISSUE THREAD

**Issue by ariettag** [5-pengoo/Therabot#20]
Hello @jperedadnr,

Thank you so much for all of your attentive help thus far. I am currently tackling the *final* hurdle in my app development process: deploying to Android. However, after installing (and updating) the proper software, as well as editing my pom.xml, the program fails with `mvn gluonfx:build`. I'm not sure why. I have attached the log files for reference.

[client-debug0.log](https://github.com/5-pengoo/Therabot/files/7384971/client-debug0.log)
[process-compile-1634773086040.log](https://github.com/5-pengoo/Therabot/files/7384972/process-compile-1634773086040.log)

**Comment by jperedadnr** [comment]
Long story short: carefully remove the `com.sun.javafx.font.coretext.**` blocks from the `META-INF/native-image/jni-config.json` file.

From the files you sent me, these lines should go away:

```
{
  "name":"com.sun.javafx.font.coretext.CGAffineTransform",
  "fields":[
    {"name":"a"}, 
    {"name":"b"}, 
    {"name":"c"}, 
    {"name":"d"}, 
    {"name":"tx"}, 
    {"name":"ty"}
  ],
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.sun.javafx.font.coretext.CGPoint",
  "fields":[
    {"name":"x"}, 
    {"name":"y"}
  ],
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.sun.javafx.font.coretext.CGRect",
  "fields":[
    {"name":"origin"}, 
    {"name":"size"}
  ],
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.sun.javafx.font.coretext.CGSize",
  "fields":[
    {"name":"height"}, 
    {"name":"width"}
  ],
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
```
Then save, and run again `mvn -Pandroid gluonfx:build`.

Do the same if after running `mvn -Pandroid gluonfx:build` you get similar errors. 

Detailed explanation: you first ran `mvn gluonfx:runagent` on your Mac, that uses JavaFX for Mac, which is a little bit different than JavaFX for Linux. So the `META-INF/native-image/` files you generated might have some JavaFX classes that are Mac specific, and don't exist on Linux. You can edit those files and remove ("carefully") the classes that are not found while compiling (either reflection or jni json files), and try to build again.

Note: You could still build again for iOS if you need to even after you remove those lines, as most of them should be added by Substrate already.

**Comment by ariettag** [comment]
@jperedadnr that makes sense. Thanks for the detailed response.

However, I'm not sure what you mean by 'Do the same if after running `mvn -Pandroid gluonfx:build` you get similar errors.' After removing those lines, running, and getting similar errors, I checked the `jni-config.json` file and those lines are still removed, so I can't do the same.

**Comment by ariettag** [comment]
@jperedadnr there's a `com.sun.javafx.font.coretext.**` block in the reflect-config.json file. Should I remove that?

**Comment by jperedadnr** [comment]
Yes, that is a mac only class. That's what I meant before: run again and if the build fails because other classes being found in those files that are not available on Linux, then remove these classes from the json files and try again.

**Comment by ariettag** [comment]
Ok, @jperedadnr, I did that and am now getting different errors. Ubuntu will go to a certain point in the build and then stop. Even when I left it running all day, it didn't go past this one stage. I have attached a screenshot for reference, as well as the logs that are printed once I do ^C.
![Screenshot 2021-10-23 134305](https://user-images.githubusercontent.com/79435335/138570932-df3bacf8-a015-40d1-ac5e-89dfaccfa3d8.jpg)
[client-debug0.log](https://github.com/5-pengoo/Therabot/files/7403633/client-debug0.log)
[process-compile-1635015193391.log](https://github.com/5-pengoo/Therabot/files/7403634/process-compile-1635015193391.log)

**Comment by ariettag** [comment]
@jperedadnr I've been trying different ways to approach this issue. This time, after rebooting my computer multiple times, I ran it again, and it was able to self-diagnose after 1 hour and 10 minutes, giving the same error of exceeding `300 seconds during CFG traversal`. I can't figure out what this issue is, and I'm in a bit of a time crunch. Could you please help?

**Comment by jperedadnr** [comment]
You have most certainly a memory issue on your Linux machine.

I've tested on my Linux machine with the zip you sent me a while ago, and that works fine, it builds in about 3:30 minutes. I have 16 GB RAM and 8 GB swap memory. What are your specs? Adding RAM is not easy of course, but swap memory can be done if you have enough disk space.

**Comment by ariettag** [comment]
@jperedadnr hm. My computer has been rapidly running out of storage, so I'm not sure if that has impacted anything. I have attached the output from `top` and `free`, respectively.

top - 12:33:20 up 9 min,  0 users,  load average: 0.00, 0.00, 0.00                                                      Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie                                                    %Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st                                         MiB Mem :   6276.5 total,   6140.1 free,     77.7 used,     58.7 buff/cache                                             MiB Swap:   2048.0 total,   2048.0 free,      0.0 used.   6046.7 avail Mem                                                                                                                                                                        PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                               82 superpe+  20   0   10876   3700   3184 R   0.3   0.1   0:00.25 top                                                    1 root      20   0     900    524    464 S   0.0   0.0   0:00.06 init                                                   7 root      20   0     900     80     20 S   0.0   0.0   0:00.00 init                                                   8 root      20   0     900     80     20 S   0.0   0.0   0:00.06 init                                                   9 superpe+  20   0   10036   5060   3348 S   0.0   0.1   0:00.15 bash     

               total        used        free      shared  buff/cache   available
Mem:        6427128       79480     6288604          68       59044     6192576
Swap:       2097152           0     2097152

**Comment by ariettag** [comment]
@jperedadnr so I figured out how to add swap memory, but I'm getting a different error. For some reason, it is not creating log files, but I can attach the printed error in my console. Could you help me out?

`Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1071)
Caused by: java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:173)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:171)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at javafx.graphics/com.sun.glass.ui.Application.run(Application.java:144)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:280)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:288)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:409)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
        ... 5 more
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.openjfx.JavaFXBaseMojo.executeCommandLine (JavaFXBaseMojo.java:567)
    at org.openjfx.JavaFXBaseMojo.executeCommandLine (JavaFXBaseMojo.java:434)
    at org.openjfx.JavaFXRunMojo.execute (JavaFXRunMojo.java:105)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:567)
        at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:434)
        at org.openjfx.JavaFXRunMojo.execute(JavaFXRunMojo.java:105)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.977 s
[INFO] Finished at: 2021-10-28T16:05:15-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.openjfx:javafx-maven-plugin:0.0.6:run (default-cli) on project Therabot: Error: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.228 s
[INFO] Finished at: 2021-10-28T16:05:15-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.7:run (default-cli) on project Therabot: Error, javafx:run@default-cli failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by jperedadnr** [comment]
hmm, `Unable to open DISPLAY` usually happens when you run without a monitor to render the application. Are you running your Linux on a virtual machine? 

I see this happens with `gluonfx:run`. Are you able to run any JavaFX application? If it was working before, what did you change??

Add to your `main` method: `System.setProperty("prism.verbose","true");` (right before `launch`), run again, and post the output.

**Comment by ariettag** [comment]
@jperedadnr I'm running the zip of Therabot that I sent you on Windows 10 with Ubuntu. Although this project has never successfully run on my Windows, the terminal never showed this error. Adding that line before `launch` in my `main` method did not work.

Maybe this is the problem?
`[WARNING] Target 'android' will be ignored for 'gluonfx:run' goal on the host machine
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.superpengoo:Therabot:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin com.gluonhq:gluonfx-maven-plugin @ line 119, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]`

**Comment by jperedadnr** [comment]
If you are using WSL2, there is no GUI available (yet), and therefore you can't run any JavaFX app because there is no display to render to.

This doesn't mean you can't use the plugin to build the apk. Just run:
```
mvn -Pandroid gluonfx:build gluonfx:package
```

**Comment by ariettag** [comment]
@jperedadnr that helped a little bit, however now it's gone back to the earlier problem. After multiple hours of waiting (and my computer being very slow), it still stayed at 
`[Fri Oct 29 16:16:31 PDT 2021][INFO] [SUB] [com.superpengoo.therabot:1500]      (parse):  36,383.47 ms,  3.88 GB`. 

I've added 9 GB's of swap memory, too. 
` free -g`
`            total        used        free      shared  buff/cache   available
Mem:              6           0           5           0           0           5
Swap:             9           0           9`

You said it worked for you, so could you send me your zip of the package? I can give you my Google Play information. I need this app to be on the Google Play store by Monday.

**Comment by jperedadnr** [comment]
The build phase is the one that has more machine requirements. So I can take care of it. 

Once it is done you should be able to resume the package task.

 I just need the latest zip of your code (just pom and src folder). Then I’ll zip and send you the target folder and you’ll run the package goal.

however we won’t be able to run many iterations this way, should anything fails during the process. 

It is probably much simpler if you try on a friend’s Linux machine? Also GitHub has Actions to run builds on any platform. 

You could easily setup a small workflow with the build part (you’ll need a GitHub repo with pom and src). See for reference  https://github.com/gluonhq/hello-gluon-ci/blob/master/.github/workflows/android.yml

**Comment by ariettag** [comment]
@jperedadnr that sounds great; thank you. 

The only other computer that I have access to is my Mac, which I used to build the iOS app, and GitHub isn't allowing me to push my changes, even if I try to hide the big files. 

Once I have more time, I'll probably follow one of those paths (either downloading a Linux virtual machine on my Mac or creating a new repo with the GitHub workflow).

https://drive.google.com/file/d/1RKnz9Ky4L0BVJTsAdpUtKL_v5j3tTE8N/view?usp=sharing

**Comment by jperedadnr** [comment]
Here you go: https://drive.google.com/file/d/112H-ytpKyzIbf9lHmQkkdECSXaBUHWcw/view?usp=sharing
Just unzip (on a different folder, don't overwrite yours), and resume:
`mvn -Pandroid gluonfx:package`

**Comment by ariettag** [comment]
@jperedadnr thanks! I was able to successfully package and change icon images, however when I try to upload it to the Google Play Console I get errors which I'm not sure how to solve. 

Firstly, I get errors stating that I need to make the package not debug-able, but under release mode. I noticed that it mentioned that in the Gluon Docs, however I thought that I was taking care of that by adding by `<releaseConfiguration>` details, since little further information was given on the documentation.

Secondly, it says I need to change my API level to 30, which I could also not find any explanation for on the docs.

Could you help me figure out what I'm doing wrong? The screenshot is attached below.

![Screenshot 2021-10-31 001808](https://user-images.githubusercontent.com/79435335/139572839-8db44be4-89fd-4dd0-8ddb-ed9e88b0fc74.jpg)

**Comment by jperedadnr** [comment]
We updated the plugin to use version 30 a while [ago](https://github.com/gluonhq/substrate/commit/4a570a539619a8b2dc12cf754799e131b8df0b01). 
You just need to bump it to 1.0.8 on your pom (now you have 1.0.7).

Then unzip the zip again, and run `gluonfx:package. that should work.

Verify that the manifest at: `target/gluonfx/aarch64-android/gvm/android_project/app/build/intermediates/merged_manifests/debug/AndroidManifest.xml` has:

```    
<uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="30" />
```

About signing, your pom is somehow confusing as you have included the plugin twice.
```
<plugin>
                <groupId>com.gluonhq</groupId>
                <artifactId>gluonfx-maven-plugin</artifactId>
                <version>${gluonfx.plugin.version}</version>
                <configuration>
                    <releaseConfiguration>
 ...
                </configuration>
            </plugin>

	<plugin>
    		<groupId>com.gluonhq</groupId>
    		<artifactId>gluonfx-maven-plugin</artifactId>
    		<version>1.0.8</version>
    		<configuration>
        		<target>android</target>
        		<mainClass>${mainClassName}</mainClass>
    		</configuration>
	</plugin>
```

Also, when you run the package goal you can see in the logs something like:
```
[Sun Oct 31 11:05:54 CET 2021][SEVERE] The key store path C:\Users\Arietta Goshtasby\Desktop\Therabot Files\upload-keystore.jks is not valid. Using Debug signing configuration
```
That means that if something goes wrong with your release configuration, it will default to debug.

So I suggest you copy the keystore file to the project root folder, and modify the pom to use one plugin only, like:

```
<plugin>
                <groupId>com.gluonhq</groupId>
                <artifactId>gluonfx-maven-plugin</artifactId>
                <version>1.0.8</version>
    		<configuration>
        	     <target>android</target>
                    <releaseConfiguration>
            		<versionCode>1</versionCode>
            		<providedKeyStorePath>upload-keystore.jks</providedKeyStorePath>
            		<providedKeyStorePassword>therabot</providedKeyStorePassword>
            		<providedKeyAlias>upload</providedKeyAlias>
            		<providedKeyAliasPassword>therabot</providedKeyAliasPassword>
        	    </releaseConfiguration>
                    <attachList>
                        <list>browser</list>
                        <list>display</list>
                        <list>lifecycle</list>
                        <list>statusbar</list>
                        <list>storage</list>
                    </attachList>
                    <mainClass>${mainClassName}</mainClass>
                    <verbose>true</verbose>
                </configuration>
            </plugin>
```
then run again `mvn gluonfx:package` and verify that you have the following file for instance:

`target/gluonfx/aarch64-android/gvm/android_project/app/build/outputs/apk/release/app-release.apk`.

(The final apk will be still at `target/gluonfx/aarch64-android/gvm/Therabot.apk`)

**Comment by ariettag** [comment]
@jperedadnr that's very helpful; thank you so much. I do want to point out, though, that when I put the `upload-keystore.jks` file into the local directory (`Therabot\target\gluonfx\aarch64-android\gvm\android_project\app`) and ran the package goal, it would automatically delete the file. I had to quickly paste it back into the directory for the packaging to work. Hopefully that is helpful for future Gluon bug fixes.

Unless another catastrophe happens like what initially did with Apple (which it shouldn't, right? the proper serialization files are there?), I am finished with the Google Play uploading process and am awaiting approval. Thank you again for all of your help; I'll close this issue when the app is successfully running on the Google Play Store.

**Comment by jperedadnr** [comment]
Glad it worked!

I meant before that you copied the keystore file to the project root folder (the Therabot folder itself).
You shouldn't add files to `Therabot/target/*`, as  it gets deleted any time you run `mvn clean ...`

However I realize now that `mvn gluonfx:package`, which has root in Therabot, actually runs the gradle project under `Therabot\target\gluonfx\aarch64-android\gvm\android_project`, so that's why an absolute path is usually recommended.

**Comment by ariettag** [comment]
@jperedadnr I thought you said that it would not have the same user log in error that it did with the Apple, but after uploading on the Google Play Store, the same error occurs. This is significantly delaying my app delay process; could you please help me figure this out as soon as possible?

**Comment by jperedadnr** [comment]
You did send me the "working" source, and I built the native image for you. I didn't check the contents... Now I see that the serialization file at Therabot/src/main/resources/META-INF/native-image is empty, which explains the login issue, as we have already discussed.
It all comes down to not having a proper repository with everything properly setup, version control, tags, history...
I can build a new native image for you again anyway.

**Comment by jperedadnr** [comment]
I've run gluonfx:runagent to generate the json files. Built and installed to test locally on my device, login on a second run works fine.

Link updated with latest native image: https://drive.google.com/file/d/112H-ytpKyzIbf9lHmQkkdECSXaBUHWcw/view?usp=sharing

**Comment by ariettag** [comment]
@jperedadnr perfect; thank you so much. I'll let you know if everything runs smoothly once it has been uploaded to the Google Play Store.

**Comment by ariettag** [comment]
@jperedadnr I tried downloading it multiple times, and it keeps saying this:
![Screenshot 2021-11-12 135335](https://user-images.githubusercontent.com/79435335/141539088-98166044-c291-4457-8656-591dd4908bc9.jpg)

**Comment by jperedadnr** [comment]
Sorry, try again: https://drive.google.com/file/d/1uJy6iv964JAyvYAj6kpjjeFvswWyAILK/view?usp=sharing

**Comment by ariettag** [comment]
@jperedadnr ok, that works, but now I'm getting the following errors in the Google Play Store. Could you help me out?
![Screenshot 2021-11-12 160730](https://user-images.githubusercontent.com/79435335/141597259-732aa5ac-4fc9-42a1-8800-794e5f6b5bb2.jpg)

**Comment by jperedadnr** [comment]
We've been through the first one, already, see previous comments. You need to set the correct providedKeyStorePath (try an absolute path, outside the target folder)

The version code is easy, you can't use the same code, you need to increase it.

**Comment by ariettag** [comment]
Hello,

Sorry for the late response. The Android build has been on the Google Play Store for a few days now. I would appreciate it if you could download it on your Apple and/or Android devices!

I really appreciate all of your help throughout this process. Gluon has exceeded my expectations in all domains; I'm so glad I decided to develop my app with Gluon Mobile! I will definitely recommend Gluon's services to all who intend on using Java to create powerful, cross-platform applications.

So, until next time, thanks again for your invaluable assistance!

**Comment by jperedadnr** [comment]
Great, I'll give it a try. 
I'm really glad it finally worked out for you!
